kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: foundry-data-pvc
  namespace: foundry-vtt
  labels:
   app: foundry
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi