apiVersion: v1
kind: PersistentVolume
metadata:
 name: foundry-data
 namespace: foundry-vtt
 labels:
  app: foundry
spec:
  capacity:
    storage: 512Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
   path: <path where foundry files will be stored on host>
  nodeAffinity:
   required:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - <name of kubernetes host that you would like foundry to be installed on>
